apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: solr
  labels:
    app: zookeeper
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
    - port: 2181
      name: client
  clusterIP: None
  selector:
    app: zookeeper
