# this allows for max 1 instance of ZK to be unavailable - should be updated based on the number of instances being deployed to maintain a quorum
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
  namespace: solr
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-statefulset
  namespace: solr
  labels:
    app: zookeeper
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper-service
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: solr
      affinity:
        # this causes K8s to only schedule only one Zookeeper pod per node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zookeeper
          image: zookeeper:3.4
          env:
            - name: ZK_REPLICAS
              value: "3" # informs Zookeeper of the number of intended replicas
            - name: ZK_TICK_TIME
              value: "2000"
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "mntr,conf,ruok"
            - name: ZOO_STANDALONE_ENABLED
              value: "false"
            # lists all of the Zookeeper servers that are part of this cluster
            - name: ZOO_SERVERS
              value: server.1=zookeeper-statefulset-0.zookeeper-service:2888:3888;2181 server.2=zookeeper-statefulset-1.zookeeper-service:2888:3888;2181 server.3=zookeeper-statefulset-2.zookeeper-service:2888:3888;2181
            - name: ZOO_CFG_EXTRA
              value: "quorumListenOnAllIPs=true electionPortBindRetry=0" # quorumListenOnAllIPs allows ZK to listen on all IP addresses for leader election/follower, electionPortBindRetry disables the max retry count as other ZK instances are spinning up
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: server
              containerPort: 2888
              protocol: TCP
            - name: election
              containerPort: 3888
              protocol: TCP
          volumeMounts:
            - name: zookeeper-pv
              mountPath: /data
          livenessProbe:
            # runs a shell script to ping the running local Zookeeper instance, which responds with "imok" once the instance is ready
            exec:
              command:
                - sh
                - -c
                - 'OK=$(echo ruok | nc 127.0.0.1 2181); if [ "$OK" = "imok" ]; then	exit 0; else exit 1; fi;'
            initialDelaySeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            # runs a shell script to ping the running local Zookeeper instance, which responds with "imok" once the instance is ready
            exec:
              command:
                - sh
                - -c
                - 'OK=$(echo ruok | nc 127.0.0.1 2181); if [ "$OK" = "imok" ]; then	exit 0; else exit 1; fi;'
            initialDelaySeconds: 20
            timeoutSeconds: 5
      initContainers:
        # each ZK instance requires an ID specification - since we can't set the ID using env variables, this init container sets the ID for each instance incrementally through a file on a volume mount
        - name: zookeeper-id
          image: busybox:latest
          command:
            - sh
            - -c
            - echo $((${HOSTNAME##*-}+1)) > /data-new/myid
          volumeMounts:
            - name: zookeeper-pv
              mountPath: /data-new
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-pv
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-premium
        resources:
          requests:
            storage: 1Gi
