apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitecore-cm-deployment
  namespace: sitecore
  labels:
    app: sitecore
    role: cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitecore
  template:
    metadata:
      labels:
        app: sitecore
        role: cm
    spec:
      containers:
        - name: sitecore-cm
          image: scr.sitecore.com/sxp/sitecore-xp0-cm:10.0.0-ltsc2019
          ports:
            - name: web
              containerPort: 80
          envFrom:
            - configMapRef:
                name: sitecore-configmap
          resources:
            limits:
              memory: 4Gi
              cpu: 1
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: sitecore-cm-service
<<<<<<< HEAD:sitecore/sitecore-cm.yaml
  namespace: sitecore
=======
>>>>>>> 3f53c9c (Updates):sitecore/sitecore-cm-deployment.yaml
  labels:
    app: sitecore
    role: cm
spec:
<<<<<<< HEAD:sitecore/sitecore-cm.yaml
  type: ClusterIP
  clusterIP: None
=======
>>>>>>> 3f53c9c (Updates):sitecore/sitecore-cm-deployment.yaml
  ports:
    - port: 80
  selector:
    app: sitecore
    role: cm
