apiVersion: v1
kind: Service
metadata:
  name: solr-service
  namespace: solr
  labels:
    app: solr
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8983
  selector:
    app: solr
